CTfive/coretrainer

- README.md
This was an example of creating a pull request.
> Online quick example

- app/assets/javascripts/users.coffee
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/user.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20191015174418_devise_create_users.rb
- db/migrate/20191015180907_add_user_attrtributes.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/users_factories.rb
- spec/helpers/users_helper_spec.rb
- spec/models/user_spec.rb
Adds initial schema for user database
> Adding schema

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
> adds devise views and user attributes

- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- config/routes.rb
> adds user controllers

- app/views/layouts/application.html.erb
> add alerts to top-nav

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
- spec/factories.rb
- spec/factories/users_factories.rb
- spec/helpers/users_helper_spec.rb
- spec/models/user_spec.rb
> Factorybot user

- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
added user controller and passed the test on the first try! haha
> user index controller action TDD

- Gemfile
Experimental DRY coding in the gemfile for an Rspec error in the server window
> updates gemfile to remove duplicate rspec-rails gem

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/master.scss
- app/views/static_pages/index.html.erb
> adds mini-magick gem and styles index.html

- Gemfile
- Gemfile.lock
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/simple_form.en.yml
- lib/templates/erb/scaffold/_form.html.erb
Please check out the code and merge!
> adds simple-form gem

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
Installed calendar gem without views for now, awaiting models to and view pages creation
> installs calendar gem

- app/helpers/users_helper.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20191023033435_add_fields_to_users.rb
- db/schema.rb
> adds user fields for roles

- app/assets/stylesheets/master.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- app/views/static_pages/index.html.erb
> update forms and views to reflect other repo

- app/assets/stylesheets/master.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/production.rb
- db/seeds.rb
I think I enabled a user to sign in as a client successfully... 🙃
> updated main view and devise user controller

- db/seeds.rb
Run rake db:seed to generate all of our admin profiles
> added admin seeds

- app/models/profile.rb
- db/migrate/20191024162052_remove_user_tables.rb
- db/schema.rb
- db/seeds.rb
This is like a reset button for our database schema; leaves only User table
> fixes all db.schema tables

- app/views/layouts/application.html.erb
- config/routes.rb
I added the dashboard controller, routed to dashboards/show.html.erb, and added link to nav-bar.
> adds first dashboard

- app/helpers/users_helper.rb
- app/views/devise/registrations/new.html.erb
- db/schema.rb
This should bring us all up to speed now! 😅
> fixes role bug

- app/assets/javascripts/dashboards.coffee
- app/assets/stylesheets/dashboards.scss
- app/controllers/dashboards_controller.rb
- app/helpers/dashboards_helper.rb
- app/views/dashboards/show.html.erb
- spec/controllers/dashboards_controller_spec.rb
- spec/helpers/dashboards_helper_spec.rb
Adds the client dashboard as a base for trainer.
> adds updated client dashboard

- app/controllers/dashboards_controller.rb
- app/views/dashboards/trainershow.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- db/migrate/20191027165745_add_role_to_users.rb
- db/schema.rb
This adds the links to the client and trainer dashboard depending which one you are signed up in and then sends you successfully to the dashboard via the sticky footer on the homepage
> Adds Dashboard links to sticky footer for client and trainer

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/master.scss
- app/views/layouts/application.html.erb
- app/views/static_pages/index.html.erb
got distracted on updating the front end lol
> install role gems and update homepage

- app/controllers/clients_controller.rb
- app/models/client.rb
- app/models/role.rb
- app/models/trainer.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20191030004351_rolify_create_roles.rb
- db/migrate/20191030012136_remove_roles_from_users.rb
- db/migrate/20191030012420_create_clients.rb
- db/migrate/20191031012653_add_roles_indexes_clients_trainers.rb
- db/migrate/20191031053347_add_role_id_to_users.rb
- db/schema.rb
SET UP DATABASE FOR CLIENTS!!!!! USERS => ROLES => CLIENT
IT WORKS!
> Adding.more.to.db

- app/assets/stylesheets/master.scss
- app/controllers/clients_controller.rb
- app/controllers/trainers_controller.rb
- app/models/trainer.rb
- app/views/devise/registrations/new.html.erb
- config/routes.rb
- db/migrate/20191031170606_remove_null_from_trainers_table.rb
- db/schema.rb
Still not connected but displaying in new registration form nicely now!
> Trainer connection

- app/assets/stylesheets/clients.scss
- app/assets/stylesheets/dashboards.scss
- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/form-inputs.scss
- app/assets/stylesheets/master.scss
- app/assets/stylesheets/trainers.scss
- app/views/layouts/application.html.erb
- app/views/static_pages/index.html.erb
removed dashboard link from non-user view, added padding and removed master.scss redundancy as well as some style sheets we won't need.
> Front-end polishing

- app/assets/stylesheets/master.scss
- app/views/clients/index.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- config/routes.rb
Finally finished with the damn checkboxes already... hopefully lol 👨‍💻
> Checkboxes devise

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_abbr.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_button.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_collection_label.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_floating_labels.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_multi_select.scss
- app/assets/stylesheets/simple_form-bootstrap/_simple_form-bootstrap.scss
- app/views/clients/index.html.erb
- app/views/trainers/index.html.erb
Added dashboard simple forms to trainers.index.html.erb file and client.index.html.erb file. Added multiple scss files to style those simple forms on said pages.
> adds simple forms to client and trainer dashboards and styles with css

- app/assets/javascripts/user/roles.coffee
- app/assets/stylesheets/master.scss
- app/assets/stylesheets/user/roles.scss
- app/controllers/application_controller.rb
- app/controllers/user/roles_controller.rb
- app/controllers/users_controller.rb
- app/helpers/user/roles_helper.rb
- app/helpers/users_helper.rb
- app/models/client.rb
- app/models/trainer.rb
- app/views/dashboards/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/static_pages/index.html.erb
- config/routes.rb
- db/migrate/20191030004351_rolify_create_roles.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/user/roles_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/helpers/user/roles_helper_spec.rb
- spec/helpers/users_helper_spec.rb
updates landing page button and works on client and trainer role creations. 
Zach is continuing work on this branch after a git fetch.
> User roles

- app/assets/stylesheets/simple_form_bootstrap/_form_abbr.scss
- app/assets/stylesheets/simple_form_bootstrap/_form_button.scss
- app/assets/stylesheets/simple_form_bootstrap/_form_collection_label.scss
- app/assets/stylesheets/simple_form_bootstrap/_simple_form-bootstrap.scss
- app/views/clients/index.html.erb
- app/views/trainers/index.html.erb
This code is throwing errors so do not merge. Can a teammate review this with me to see what the issue is? Thanks, Jess
> adds client and trainer simple forms to dashboards

- app/assets/stylesheets/master.scss
- app/assets/stylesheets/simple_form_bootstrap/_form_button.scss
- app/assets/stylesheets/simple_form_bootstrap/_form_collection_label.scss
- app/assets/stylesheets/simple_form_bootstrap/_simple_form-bootstrap.scss
- app/views/dashboards/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/static_pages/index.html.erb
fixes last merge with bootstrap/simpleform styling. adds images, styling, and signup buttons to homepage, also anchors 'learn more' button to the bottom of the page for cool scrolling effect.
> Down button

- app/assets/stylesheets/master.scss
- app/views/static_pages/index.html.erb
Aligned the images and text...still working on floating/wrapping the text around the images
> arranged the images and text

- app/assets/javascripts/registrations.coffee
- app/controllers/clients_controller.rb
- app/controllers/registrations_controller.rb
- app/helpers/registrations_helper.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20191106044611_add_index_on_clients_and_trainers.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/registrations_controller_spec.rb
- spec/helpers/registrations_helper_spec.rb
Create a user and see what happens 👍
> Actual.page.on.create

- app/assets/stylesheets/master.scss
- app/views/clients/edit.html.erb
- app/views/clients/index.html.erb
- app/views/clients/new.html.erb
- app/views/layouts/application.html.erb
- app/views/static_pages/index.html.erb
- app/views/trainers/edit.html.erb
- app/views/trainers/index.html.erb
- app/views/trainers/new.html.erb
These are the changes I made to work out the kinks. Nice work!
> Client.dashboard

- app/controllers/workoutlogs_controller.rb
- app/views/clients/index.html.erb
> Revert "Workoutlogs"

- app/controllers/workoutlogs_controller.rb
- app/views/clients/index.html.erb
> Revert "Revert "Workoutlogs""

- app/assets/stylesheets/master.scss
- app/views/clients/edit.html.erb
- app/views/clients/show.html.erb
- app/views/layouts/application.html.erb
- app/views/trainers/_form.html.erb
- app/views/trainers/edit.html.erb
- app/views/trainers/index.html.erb
- app/views/trainers/show.html.erb
- config/routes.rb
good update on trainer profile!
> update trainer views and fix issues

- app/assets/stylesheets/master.scss
- app/views/static_pages/index.html.erb
- app/views/trainers/show.html.erb
Experiments with a pricing feature and installs dashboard template on trainer's profile page
> updates trainer profile and root views
